name: change-readme-create-merge-request
run-name: Change Readme and Create Pull Request
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        default: jersey
        options: ["jersey", "statenisland"]

jobs:
  add_quote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get an inspirational quote
      run: |
        QUOTE="This quote is fetched from a remote api using CURL"
        echo "$QUOTE"

    - name: Update quote in readme
      run: |-
        ###### if workbranch does not exist, create it
        gh create -B workbranch
        # Set a default quote if the 
        echo "${QUOTE:=>Silence is Golden, and the right words are more better}"
        # Disable interpreting exclamation mark! as a command
        histchars=
        # Set delimiters to variables
        start_delimiter="<!-- start-quote -->"
        end_delimiter="<!-- end-quote -->"
        # Remove previous quote with its delimter
        sed -i "/$start_delimiter/,/$end_delimiter/d" README.md
        # Add the new quote to the README file
        printf "$start_delimiter\n$QUOTE\n$end_delimiter\n" >> README.md

    - name: Create Merge Request
      id: create_mr
      run: gh pr create -B master -H workbranch --title 'Merge workbranch into master' --body 'Created by Github action'
      