name: change-readme-create-merge-request
run-name: Change Readme & Create Pull Request at ${{ github.event.repository.updated_at }}
on:
  workflow_dispatch:

jobs:
  add_quote:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get an inspirational quote
      run: |
        QUOTE="This quote is fetched from a remote api using CURL"
        echo "$QUOTE"

    - name: Update quote in readme
      run: |-
        ###### if workbranch does not exist, create it
        git checkout -B workbranch
        
        # Set a default quote  
        echo "${QUOTE:=>Silence is obtuse Golden, and the right amound words are more better}"
        # Disable interpreting exclamation mark! as a command
        histchars=
        # Set delimiters to variables
        start_delimiter="<!-- start-quote -->"
        end_delimiter="<!-- end-quote -->"
        # Remove previous quote with its delimter
        sed -i "/$start_delimiter/,/$end_delimiter/d" README.md
        # Add the new quote to the README file
        printf "$start_delimiter\n$QUOTE\n$end_delimiter\n" >> README.md
        
    - name: Commit and Push
      id: commit_and_push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |-
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git diff --quiet || (git add README.md && git commit -m "Added new quote to README")
        echo "DIFF=$(git rev-parse --short origin/workbranch)" >> $GITHUB_ENV
        git push origin workbranch

    - name: Check on failures
      if: always() && steps.commit_and_push.outcome == 'failure'
      run: |-
        echo "Cannot create merge request due to commit and push failure."
        git worktree prune
        git checkout master
        git push origin --delete workbranch

    - name: Create Merge Request
      if: steps.commit_and_push.outcome == 'success'
      id: create_mr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |-
        echo "Here was the diff: ${{ github.env.DIFF }}"
        gh pr create -B master -H workbranch --title "Request to merge workbranch into master ${{ github.event.repository.updated_at }}"\
         --body "Created by Github action at: ${{ github.event.repository.updated_at }}"
      