name: Start to drive away from New Jersey
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push

jobs:
  CallStartWorkflow:
    uses: ./.github/workflows/reusable.yml
    with: 
      command: 'start-instances'
