name: Start instances in Staten Island
run-name: ${{ github.actor }} switches Start for Staten
on: 
  push

jobs:
  CallStart:
    uses: ./.github/workflows/reusable.yml
    with: 
      {command: 'start-instances', location: 'statenisland'}
