name: Stock Instances From New Jersey
run-name: use config list instances for Jersey
on: 
  push

jobs:
  CallStop:
    uses: ./.github/workflows/reusable.yml
    with: 
      command: 'stop-instances'
      location: 'jersey'
      overrides: ''
      dry_run: 'false'
